workflows:
  react-native-android:
    name: Build React Native Android APK
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      node: 16.11.1
      java: 11
    scripts:
      - name: Instalar dependências
        script: |
          yarn install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk