workflows:
  react-native-android:
    name: Build React Native Android APK
    instance_type: linux  # <-- compatível com plano gratuito
    max_build_duration: 60
    environment:
      node: 16.11.1
      java: 11
    scripts:
      - name: Instalar dependências
        script: |
          yarn install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true